
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: false,
    API_KEY: 'be25a646-467a-44ed-877f-dcf67fc5a004'
  };
